[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agent-process-demo"
version = "0.1.0"
description = "Project configured with the Parallelus Agent Process"
requires-python = ">=3.11"
